@extends('layouts.mainlayout')
@section('title','Profile')

@section('content')
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam eveniet corrupti illum tenetur suscipit incidunt fugit quae inventore possimus temporibus laudantium aut laboriosam quo delectus similique ab optio harum nam in ad atque molestiae, porro voluptate culpa. Porro necessitatibus commodi tenetur minus libero sapiente placeat, ratione temporibus voluptates delectus sit?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia debitis expedita officia placeat quia doloremque? Quibusdam, ex. Corporis iusto deleniti nesciunt, nemo quasi molestias ipsum molestiae aliquid tempora est sunt harum magni reprehenderit temporibus commodi error ut perspiciatis consequuntur. Consequuntur voluptate aut autem laudantium facere nihil ratione sapiente nisi numquam optio quo non natus magni a quisquam mollitia eius neque totam recusandae eaque, accusamus cumque ullam quidem asperiores. Quibusdam praesentium soluta odio at esse ipsam porro dolores corporis, et sed aspernatur suscipit consectetur libero ad illum? Iure ab ipsam, cum natus earum incidunt laboriosam tempore voluptatum nulla libero cumque non.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam eveniet corrupti illum tenetur suscipit incidunt fugit quae inventore possimus temporibus laudantium aut laboriosam quo delectus similique ab optio harum nam in ad atque molestiae, porro voluptate culpa. Porro necessitatibus commodi tenetur minus libero sapiente placeat, ratione temporibus voluptates delectus sit?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia debitis expedita officia placeat quia doloremque? Quibusdam, ex. Corporis iusto deleniti nesciunt, nemo quasi molestias ipsum molestiae aliquid tempora est sunt harum magni reprehenderit temporibus commodi error ut perspiciatis consequuntur. Consequuntur voluptate aut autem laudantium facere nihil ratione sapiente nisi numquam optio quo non natus magni a quisquam mollitia eius neque totam recusandae eaque, accusamus cumque ullam quidem asperiores. Quibusdam praesentium soluta odio at esse ipsam porro dolores corporis, et sed aspernatur suscipit consectetur libero ad illum? Iure ab ipsam, cum natus earum incidunt laboriosam tempore voluptatum nulla libero cumque non.
       
    </p>
@endsection